// <auto-generated />
namespace AccountantNew.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class disableOnDeleteCascade2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(disableOnDeleteCascade2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708250432117_disableOnDeleteCascade2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
